// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v3.21.12
// source: bluerpc/bluerpc.proto

package bluesdp_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BlueHeartBeat struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServiceName string `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	IpAddress   string `protobuf:"bytes,2,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
}

func (x *BlueHeartBeat) Reset() {
	*x = BlueHeartBeat{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bluerpc_bluerpc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BlueHeartBeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlueHeartBeat) ProtoMessage() {}

func (x *BlueHeartBeat) ProtoReflect() protoreflect.Message {
	mi := &file_bluerpc_bluerpc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlueHeartBeat.ProtoReflect.Descriptor instead.
func (*BlueHeartBeat) Descriptor() ([]byte, []int) {
	return file_bluerpc_bluerpc_proto_rawDescGZIP(), []int{0}
}

func (x *BlueHeartBeat) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *BlueHeartBeat) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

type BlueHeartBeatResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Reply string `protobuf:"bytes,1,opt,name=reply,proto3" json:"reply,omitempty"`
}

func (x *BlueHeartBeatResponse) Reset() {
	*x = BlueHeartBeatResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bluerpc_bluerpc_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BlueHeartBeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlueHeartBeatResponse) ProtoMessage() {}

func (x *BlueHeartBeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bluerpc_bluerpc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlueHeartBeatResponse.ProtoReflect.Descriptor instead.
func (*BlueHeartBeatResponse) Descriptor() ([]byte, []int) {
	return file_bluerpc_bluerpc_proto_rawDescGZIP(), []int{1}
}

func (x *BlueHeartBeatResponse) GetReply() string {
	if x != nil {
		return x.Reply
	}
	return ""
}

type GetRegistredServiceList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServiceName string `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
}

func (x *GetRegistredServiceList) Reset() {
	*x = GetRegistredServiceList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bluerpc_bluerpc_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRegistredServiceList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRegistredServiceList) ProtoMessage() {}

func (x *GetRegistredServiceList) ProtoReflect() protoreflect.Message {
	mi := &file_bluerpc_bluerpc_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRegistredServiceList.ProtoReflect.Descriptor instead.
func (*GetRegistredServiceList) Descriptor() ([]byte, []int) {
	return file_bluerpc_bluerpc_proto_rawDescGZIP(), []int{2}
}

func (x *GetRegistredServiceList) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

type ServiceDetail struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IpAddress string `protobuf:"bytes,2,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
}

func (x *ServiceDetail) Reset() {
	*x = ServiceDetail{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bluerpc_bluerpc_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServiceDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceDetail) ProtoMessage() {}

func (x *ServiceDetail) ProtoReflect() protoreflect.Message {
	mi := &file_bluerpc_bluerpc_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceDetail.ProtoReflect.Descriptor instead.
func (*ServiceDetail) Descriptor() ([]byte, []int) {
	return file_bluerpc_bluerpc_proto_rawDescGZIP(), []int{3}
}

func (x *ServiceDetail) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

type RespondRegistredServiceList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ips []*ServiceDetail `protobuf:"bytes,1,rep,name=ips,proto3" json:"ips,omitempty"`
}

func (x *RespondRegistredServiceList) Reset() {
	*x = RespondRegistredServiceList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bluerpc_bluerpc_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RespondRegistredServiceList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespondRegistredServiceList) ProtoMessage() {}

func (x *RespondRegistredServiceList) ProtoReflect() protoreflect.Message {
	mi := &file_bluerpc_bluerpc_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespondRegistredServiceList.ProtoReflect.Descriptor instead.
func (*RespondRegistredServiceList) Descriptor() ([]byte, []int) {
	return file_bluerpc_bluerpc_proto_rawDescGZIP(), []int{4}
}

func (x *RespondRegistredServiceList) GetIps() []*ServiceDetail {
	if x != nil {
		return x.Ips
	}
	return nil
}

var File_bluerpc_bluerpc_proto protoreflect.FileDescriptor

var file_bluerpc_bluerpc_proto_rawDesc = []byte{
	0x0a, 0x15, 0x62, 0x6c, 0x75, 0x65, 0x72, 0x70, 0x63, 0x2f, 0x62, 0x6c, 0x75, 0x65, 0x72, 0x70,
	0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x51, 0x0a, 0x0d, 0x42, 0x6c, 0x75, 0x65, 0x48,
	0x65, 0x61, 0x72, 0x74, 0x42, 0x65, 0x61, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x69,
	0x70, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x69, 0x70, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x22, 0x2d, 0x0a, 0x15, 0x42, 0x6c,
	0x75, 0x65, 0x48, 0x65, 0x61, 0x72, 0x74, 0x42, 0x65, 0x61, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x65, 0x70, 0x6c, 0x79, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x72, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x3c, 0x0a, 0x17, 0x47, 0x65, 0x74,
	0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x65, 0x64, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x4c, 0x69, 0x73, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x2e, 0x0a, 0x0d, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x12, 0x1d, 0x0a, 0x0a, 0x69, 0x70, 0x5f, 0x61,
	0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x69, 0x70,
	0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x22, 0x3f, 0x0a, 0x1b, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x64, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x65, 0x64, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x20, 0x0a, 0x03, 0x69, 0x70, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x44, 0x65, 0x74,
	0x61, 0x69, 0x6c, 0x52, 0x03, 0x69, 0x70, 0x73, 0x32, 0x94, 0x01, 0x0a, 0x17, 0x42, 0x6c, 0x75,
	0x65, 0x53, 0x44, 0x50, 0x48, 0x65, 0x61, 0x72, 0x74, 0x42, 0x65, 0x61, 0x74, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x34, 0x0a, 0x08, 0x53, 0x61, 0x79, 0x41, 0x6c, 0x69, 0x76, 0x65,
	0x12, 0x0e, 0x2e, 0x42, 0x6c, 0x75, 0x65, 0x48, 0x65, 0x61, 0x72, 0x74, 0x42, 0x65, 0x61, 0x74,
	0x1a, 0x16, 0x2e, 0x42, 0x6c, 0x75, 0x65, 0x48, 0x65, 0x61, 0x72, 0x74, 0x42, 0x65, 0x61, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x43, 0x0a, 0x07, 0x47, 0x65,
	0x74, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x18, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x67, 0x69, 0x73,
	0x74, 0x72, 0x65, 0x64, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x1a,
	0x1c, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x64, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72,
	0x65, 0x64, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x00, 0x42,
	0x11, 0x5a, 0x0f, 0x2e, 0x2f, 0x62, 0x6c, 0x75, 0x65, 0x73, 0x64, 0x70, 0x2d, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_bluerpc_bluerpc_proto_rawDescOnce sync.Once
	file_bluerpc_bluerpc_proto_rawDescData = file_bluerpc_bluerpc_proto_rawDesc
)

func file_bluerpc_bluerpc_proto_rawDescGZIP() []byte {
	file_bluerpc_bluerpc_proto_rawDescOnce.Do(func() {
		file_bluerpc_bluerpc_proto_rawDescData = protoimpl.X.CompressGZIP(file_bluerpc_bluerpc_proto_rawDescData)
	})
	return file_bluerpc_bluerpc_proto_rawDescData
}

var file_bluerpc_bluerpc_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_bluerpc_bluerpc_proto_goTypes = []interface{}{
	(*BlueHeartBeat)(nil),               // 0: BlueHeartBeat
	(*BlueHeartBeatResponse)(nil),       // 1: BlueHeartBeatResponse
	(*GetRegistredServiceList)(nil),     // 2: GetRegistredServiceList
	(*ServiceDetail)(nil),               // 3: ServiceDetail
	(*RespondRegistredServiceList)(nil), // 4: RespondRegistredServiceList
}
var file_bluerpc_bluerpc_proto_depIdxs = []int32{
	3, // 0: RespondRegistredServiceList.ips:type_name -> ServiceDetail
	0, // 1: BlueSDPHeartBeatService.SayAlive:input_type -> BlueHeartBeat
	2, // 2: BlueSDPHeartBeatService.GetList:input_type -> GetRegistredServiceList
	1, // 3: BlueSDPHeartBeatService.SayAlive:output_type -> BlueHeartBeatResponse
	4, // 4: BlueSDPHeartBeatService.GetList:output_type -> RespondRegistredServiceList
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_bluerpc_bluerpc_proto_init() }
func file_bluerpc_bluerpc_proto_init() {
	if File_bluerpc_bluerpc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_bluerpc_bluerpc_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BlueHeartBeat); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bluerpc_bluerpc_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BlueHeartBeatResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bluerpc_bluerpc_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRegistredServiceList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bluerpc_bluerpc_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServiceDetail); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bluerpc_bluerpc_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RespondRegistredServiceList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_bluerpc_bluerpc_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bluerpc_bluerpc_proto_goTypes,
		DependencyIndexes: file_bluerpc_bluerpc_proto_depIdxs,
		MessageInfos:      file_bluerpc_bluerpc_proto_msgTypes,
	}.Build()
	File_bluerpc_bluerpc_proto = out.File
	file_bluerpc_bluerpc_proto_rawDesc = nil
	file_bluerpc_bluerpc_proto_goTypes = nil
	file_bluerpc_bluerpc_proto_depIdxs = nil
}
